<a href="https://colab.research.google.com/github/Divyanridegree/Python-project/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy- Numeric Python
# Most powerful package - Library

#Numpy- Dimensions
# A-One Dimensionaal Array
# [A,B] || [ A
             #B ]-Two Dimensional Array- Row ||column
# Three Dimensional
# Array-Storing,Manipulating,Similar Data Type
# Faster than any mathematical functions
# Convenient compared to other packages
# Memory Efficiency
# Support Multi Dimensional Arrays
#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
# memory optimizatin(Numpy)>memory optimization(List operations)

In [2]:
# Install numpy - pip3 install numpy // pip install numpy

In [3]:
import numpy as np

In [4]:
# create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [5]:
# create 2D array-Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [6]:
# creating Arrays with default values

allZeros = np.zeros((2,3))
print (allZeros)

# creating matrix with all values of elements as '1'

allOnes = np.ones((2,3))
print (allOnes)

#creating matrix with all values of elements 'constant value -n ~ Fill value'


allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [7]:
# create an identity matrix -I- Square matrix
identity = np.eye(4)
print(identity)

# Identity matrix-Aii = 1 && Aij = 0
# For all A belongs to R M×N
#Aij-

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Creare a random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

#between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.60269784 0.00099316 0.94047479]
 [0.44315502 0.71603039 0.67239481]
 [0.35033248 0.71998894 0.5586404 ]]
[[10 11 10]
 [12 17 17]
 [17 12 11]]


In [9]:
# Array properties
arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)
# shape of the Array
print (f'The shape of the array is {arr.shape}')
# size of the Array
print(f'The size of the array is {arr.size}')
# datatype of the Array
print(f'The Datatype of the array is {arr.dtype}')
# dimensions of array
print(f'The Dimensions of the array is {arr.ndim} ')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Datatype of the array is int64
The Dimensions of the array is 2 


In [10]:
# Indexing and Slicing
# Access the elements in 1D array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])# first row with all columns
print(arr2[:,0])# first column with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [11]:
# l1 = []
# [l1.append(_) for _ in range(10)]
l1 = np.arange(0,10)
print (l1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
l1 = np.arange(10,0,-1)
print(l1)

[10  9  8  7  6  5  4  3  2  1]


In [13]:
l1 = np.arange(10,-10,-3)
print(l1)

[10  7  4  1 -2 -5 -8]


In [14]:
# Mathematical Operations
a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'the sum of a and b is {a+b}')
print(f'the diff of a and b is {a-b}')
print(f'the product of a and b is {a*b}')
print(f'the division of a and b is {a/b}')

the sum of a and b is [4 6 8]
the diff of a and b is [-2 -2 -2]
the product of a and b is [ 3  8 15]
the division of a and b is [0.33333333 0.5        0.6       ]


In [15]:
# Matrix Multiplication
b1 = np.array([[1,2,3],[3,4,5]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product --- product =AB -- m×n --B n×p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [48 65]]


In [16]:
b1

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
b2

array([[5, 6],
       [7, 8],
       [1, 3]])

In [18]:
print(b1)

[[1 2 3]
 [3 4 5]]


In [21]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [20]:
import numpy as np

In [22]:
# Recap
arr = np.array([[1,2,3],[4,5,6]])

In [23]:
type(arr)

numpy.ndarray

In [24]:
# Dot product- m×n || n×p
arr1 = np.random.randint(1,2,(1,2))

In [25]:
arr.shape
arr1.shape

(1, 2)

In [26]:
result = np.dot(arr1,arr)

In [27]:
print(result)

[[5 7 9]]


In [28]:
r1 = np.random.randint(10,20,(3,3))

In [29]:
print(r1)

[[11 18 17]
 [17 16 18]
 [15 19 10]]


In [30]:
r2 = np.eye(3)

In [31]:
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# r1,I
result2 = np.dot(r1,r2)

In [33]:
print (result2)

[[11. 18. 17.]
 [17. 16. 18.]
 [15. 19. 10.]]


In [34]:
# Mathematical Operations
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [35]:
print(t1)
print(t2)

[[5 3 4]
 [5 3 5]
 [4 3 4]]
[[4 4 3]
 [5 4 4]
 [3 5 4]]


In [36]:
t3 = t1*t2

In [37]:
print(t3)

[[20 12 12]
 [25 12 20]
 [12 15 16]]


In [38]:
# Matrix Multiplication
result = np.dot(arr1,arr)

In [39]:
# Statistical operations
mean = t3.mean()
max = t3.max
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [41]:
print (median)

15.0


In [48]:
print(mean)

16.0


In [49]:
print(std)

4.447221354708778


In [42]:
# Trigonometric Operations
# sin(x)
# cos(x)
# tan(x)- sin(x)/cos(x)
# cot(x)-1/tan(x)
# sec(x)-1/cos(x)
# cosec(x)-1/sin(x)

In [43]:
angles = np.array([10,15,30,45,60,75,90])
# Sin(array)
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [44]:
print(result)
print(result1)
print(result2)

[0.17364818 0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[9.84807753e-01 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[1.76326981e-01 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [45]:
arr = np.array([1,2,3,4,5,6])
# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [46]:
# Stacking the data
arr1 = np.array([1,2,3,4,])
arr2 = np.array([10,20,30,40])
# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f'The shape of arr3 is {arr3.shape}')

# Horizontal Stacking
arr4 = np.hstack((arr1,arr2))
print(f'The shape of arr4 is {arr4.shape}')
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [47]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

Farr = arr[arr>40]

print (Farr)

[50 60 70 80]
